### ISSUE TITLE
"wrong number of arguments" in vectorized call on DataArrays

### ISSUE THREAD

**Issue by Les0me** [DeniseCaiLab/minian#48] opened 2020-02-13 15:22 UTC
Hi,

When running the pipeline_noted.ipynb with the demo movies I get the following error:
 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-24aa6b1de449> in <module>
      1 hv.output(size=output_size)
      2 if interactive:
----> 3     display(visualize_preprocess(varr_ref.isel(frame=0), denoise, method=['median'], ksize=[5, 7, 9]))

~/Downloads/minian-master/minian/visualization.py in visualize_preprocess(fm, fn, include_org, **kwargs)
   1365         for params in itt.product(*pval):
   1366             fm_res = fn(fm, **dict(zip(pkey, params)))
-> 1367             cur_im, cur_cnt = _vis(fm_res)
   1368             cur_im = cur_im.relabel('After')
   1369             cur_cnt = cur_cnt.relabel('After')

~/Downloads/minian-master/minian/visualization.py in _vis(f)
   1355         im = (hv.Image(f, kdims=['width', 'height'])
   1356                   .opts(**opts_im))
-> 1357         cnt = (hv.operation.contours(im)
   1358                    .opts(**opts_cnt))
   1359         return im, cnt

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/param/parameterized.py in __new__(class_, *args, **params)
   2810         inst = class_.instance()
   2811         inst.param._set_name(class_.__name__)
-> 2812         return inst.__call__(*args,**params)
   2813 
   2814     def __call__(self,*args,**kw):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in __call__(self, element, **kwargs)
    162         elif 'streams' not in kwargs:
    163             kwargs['streams'] = self.p.streams
--> 164         return element.apply(self, **kwargs)
    165 
    166 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/accessors.py in __call__(self, function, streams, link_inputs, dynamic, **kwargs)
    108             if hasattr(function, 'dynamic'):
    109                 inner_kwargs['dynamic'] = False
--> 110             return function(self._obj, **inner_kwargs)
    111         elif self._obj._deep_indexable:
    112             mapped = []

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in __call__(self, element, **kwargs)
    159                                       for k, el in element.items()])
    160             elif isinstance(element, ViewableElement):
--> 161                 return self._apply(element)
    162         elif 'streams' not in kwargs:
    163             kwargs['streams'] = self.p.streams

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in _apply(self, element, key)
    119         for hook in self._preprocess_hooks:
    120             kwargs.update(hook(self, element))
--> 121         ret = self._process(element, key)
    122         for hook in self._postprocess_hooks:
    123             ret = hook(self, ret, **kwargs)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/operation/element.py in _process(self, element, key)
    433         xs = element.dimension_values(0, True, flat=False)
    434         ys = element.dimension_values(1, True, flat=False)
--> 435         zs = element.dimension_values(2, flat=False)
    436 
    437         # Ensure that coordinate arrays specify bin centers

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/data/__init__.py in dimension_values(self, dimension, expanded, flat)
    768         """
    769         dim = self.get_dimension(dimension, strict=True)
--> 770         return self.interface.values(self, dim, expanded, flat)
    771 
    772 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/data/xarray.py in values(cls, dataset, dim, expanded, flat, compute)
    325             da = dask_array_module()
    326             if compute and da and isinstance(data, da.Array):
--> 327                 data = data.compute()
    328             data = cls.canonicalize(dataset, data, data_coords=data_coords,
    329                                     virtual_coords=virtual_coords)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    460                         _execute_task(task, data)  # Re-execute locally
    461                     else:
--> 462                         raise_exception(exc, tb)
    463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return core.get(self.dsk, self.outkey,
--> 942                         dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in get(dsk, out, cache)
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2089             vargs.extend([kwargs[_n] for _n in names])
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 
   2093     def _get_ufunc_and_otypes(self, func, args):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2155         """Vectorized call to `func` over positional `args`."""
   2156         if self.signature is not None:
-> 2157             res = self._vectorize_call_with_signature(func, args)
   2158         elif not args:
   2159             res = func()

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call_with_signature(self, func, args)
   2181             raise TypeError('wrong number of positional arguments: '
   2182                             'expected %r, got %r'
-> 2183                             % (len(input_core_dims), len(args)))
   2184         args = tuple(asanyarray(arg) for arg in args)
   2185 

TypeError: wrong number of positional arguments: expected 1, got 2

```
Could it be a bug due to a new version of dask/numpy like here ['fix a vectorize bug from new dask/numpy version'](https://github.com/DeniseCaiLab/minian/commit/756e4025a5177a0ac26c36afcb9a0c68c88371f1)? Using the docker isn´t working either.
Many thanks in advance!

**Comment by phildong** [comment] 2020-02-29 03:07
this seem to be caused by latest version of `xarray` 0.15 breaking compatibility with `dask` 1.x
Luckily the vectorize bug (756e4025a5177a0ac26c36afcb9a0c68c88371f1) you mentioned seem to be fixed by `xarray` 0.15 as well so there is no reason that dask has to be pinned to 1.x anymore and we can use the latest version of everything.
12dae24463ea593bd8db3ff816b55eb183912dd4 should be able to address this properly. So I'd recommend pull in those changes and start fresh (recreating the conda environment using latest environment.yml).
Alternatively if you want to stick to what has been working, `conda install -c conda-forge xarray=0.14` should be able to solve this particular problem without risking an update of the environment.

**Comment by ForoughHa** [comment] 2020-03-27 14:31
Dear Phil,

I have recently started using your package and I am now facing the same problem as stated in this issue. 
In the "denoise" step (and many of the following steps), I get the "**wrong number of arguments**" error (copied at the end of my comment)

However, I tried your solution for this issue and updated my environment.yml and recreated and reactivated my minian environment but unfortunately, I am still getting the same error. 
What I did:
I updated the environment.yml file and replaced  it with [https://github.com/DeniseCaiLab/minian/blob/12dae24463ea593bd8db3ff816b55eb183912dd4/environment.yml](https://github.com/DeniseCaiLab/minian/blob/12dae24463ea593bd8db3ff816b55eb183912dd4/environment.yml)
Then I used: cd minian/
$ conda env update --prefix ./env --file environment.yml  --prune

But as I said, I am facing the same issue. Do you have any ideas about how I can fix this?


---------The error from denoise step: ----------
-------------
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-24aa6b1de449> in <module>
      1 hv.output(size=output_size)
      2 if interactive:
----> 3     display(visualize_preprocess(varr_ref.isel(frame=0), denoise, method=['median'], ksize=[5, 7, 9]))

~/minian/minian/visualization.py in visualize_preprocess(fm, fn, include_org, **kwargs)
   1365         for params in itt.product(*pval):
   1366             fm_res = fn(fm, **dict(zip(pkey, params)))
-> 1367             cur_im, cur_cnt = _vis(fm_res)
   1368             cur_im = cur_im.relabel('After')
   1369             cur_cnt = cur_cnt.relabel('After')

~/minian/minian/visualization.py in _vis(f)
   1355         im = (hv.Image(f, kdims=['width', 'height'])
   1356                   .opts(**opts_im))
-> 1357         cnt = (hv.operation.contours(im)
   1358                    .opts(**opts_cnt))
   1359         return im, cnt

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/param/parameterized.py in __new__(class_, *args, **params)
   2810         inst = class_.instance()
   2811         inst.param._set_name(class_.__name__)
-> 2812         return inst.__call__(*args,**params)
   2813 
   2814     def __call__(self,*args,**kw):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in __call__(self, element, **kwargs)
    194             kwargs['streams'] = self.p.streams
    195         kwargs['per_element'] = self._per_element
--> 196         return element.apply(self, **kwargs)
    197 
    198 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/accessors.py in pipelined_call(*args, **kwargs)
     43 
     44             try:
---> 45                 result = __call__(*args, **kwargs)
     46 
     47                 if not in_method:

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/accessors.py in __call__(self, apply_function, streams, link_inputs, dynamic, per_element, **kwargs)
    196             if hasattr(apply_function, 'dynamic'):
    197                 inner_kwargs['dynamic'] = False
--> 198             return apply_function(self._obj, **inner_kwargs)
    199         elif self._obj._deep_indexable:
    200             mapped = []

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in __call__(self, element, **kwargs)
    190             elif ((self._per_element and isinstance(element, Element)) or
    191                   (not self._per_element and isinstance(element, ViewableElement))):
--> 192                 return self._apply(element)
    193         elif 'streams' not in kwargs:
    194             kwargs['streams'] = self.p.streams

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/operation.py in _apply(self, element, key)
    130         element_pipeline = getattr(element, '_pipeline', None)
    131 
--> 132         ret = self._process(element, key)
    133         for hook in self._postprocess_hooks:
    134             ret = hook(self, ret, **kwargs)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/operation/element.py in _process(self, element, key)
    538         xs = element.dimension_values(0, True, flat=False)
    539         ys = element.dimension_values(1, True, flat=False)
--> 540         zs = element.dimension_values(2, flat=False)
    541 
    542         # Ensure that coordinate arrays specify bin centers

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/data/__init__.py in pipelined_fn(*args, **kwargs)
    212 
    213             try:
--> 214                 result = method_fn(*args, **kwargs)
    215 
    216                 op = method_op.instance(

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/data/__init__.py in dimension_values(self, dimension, expanded, flat)
   1046         """
   1047         dim = self.get_dimension(dimension, strict=True)
-> 1048         return self.interface.values(self, dim, expanded, flat)
   1049 
   1050 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/holoviews/core/data/xarray.py in values(cls, dataset, dim, expanded, flat, compute, keep_index)
    370             da = dask_array_module()
    371             if compute and da and isinstance(data, da.Array):
--> 372                 data = data.compute()
    373             if is_cupy(data):
    374                 import cupy

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    460                         _execute_task(task, data)  # Re-execute locally
    461                     else:
--> 462                         raise_exception(exc, tb)
    463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113 
    114     import pickle as cPickle

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/optimization.py in __call__(self, *args)
    940                              % (len(self.inkeys), len(args)))
    941         return core.get(self.dsk, self.outkey,
--> 942                         dict(zip(self.inkeys, args)))
    943 
    944     def __reduce__(self):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in get(dsk, out, cache)
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2089             vargs.extend([kwargs[_n] for _n in names])
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 
   2093     def _get_ufunc_and_otypes(self, func, args):

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2155         """Vectorized call to `func` over positional `args`."""
   2156         if self.signature is not None:
-> 2157             res = self._vectorize_call_with_signature(func, args)
   2158         elif not args:
   2159             res = func()

~/opt/anaconda3/envs/minian/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call_with_signature(self, func, args)
   2181             raise TypeError('wrong number of positional arguments: '
   2182                             'expected %r, got %r'
-> 2183                             % (len(input_core_dims), len(args)))
   2184         args = tuple(asanyarray(arg) for arg in args)
   2185 

TypeError: wrong number of positional arguments: expected 1, got 2

**Comment by phildong** [comment] 2020-03-27 14:45
@ForoughHa According to conda documentation (`conda env update --help`), the `--prefix` argument specify the path to the environment. So unless your environment is actually within the minian folder, that command should throw an error and not do anything. I would recommend double-checking that. A quick way to see whether the package versions are correct is to use `conda list [package_name]`. xarray should return something >0.15 and dask should return something > 2.

That said, if you are only updating the environments you would still run into issues, since there are changes in the scripts that's necessary for the compatibility of new versions of everything. So make sure you pull all the latest changes in `dev` branch in addition to the environment yml file. Personally I found the cleanest and easiest way to do that is just start fresh and repeat the installation steps listed in the repository.

**Comment by ForoughHa** [comment] 2020-03-27 15:33
Dear Phil,

Thank you very much for your reply.

So I should first mention that due to some technical issues, I accidentally
had to start from fresh with minian just today. So this means I cloned the
repository today and I thought this would give me the latest updates but I
imagine I have cloned from the master branch and I still need to pull all
the latest from dev?
Would you please be able to tell me what command I need to use for this
pull? I have tried many ways and they all seem to be telling me everything
is up to date but I am still skeptical. What would be the best terminal
command to use to pull all updates from dev branch?

I also checked the xarray and dask versions and they seem to be >0.15 and
>2 but I understand there might be other files (rather than
environment.yml) that I haven't been able to update correctly as you
mentioned.

Best regards,
Forough

**Comment by phildong** [comment] 2020-03-27 16:44
Hey @ForoughHa . To quickly move to `dev` branch you just need to do `git checkout dev`, and you should be able to do it right after `git clone https://github.com/DeniseCaiLab/minian.git`. A quick way to check whether it works is to use `git log --oneline` and you should see the history matching up with [the history of `dev` branch](https://github.com/DeniseCaiLab/minian/commits/dev). See more detail [here](https://guides.github.com/introduction/git-handbook/).

**Comment by ForoughHa** [comment] 2020-03-28 04:36
Hi @phildong,

Thanks a lot for your help.
I started fresh and cloned minian again and it solved my problem. I have the pipeline up and running now except this time near the end of the pipeline, I faced an issue exactly like #45 . I will be posting what happened under that thread now.

**Closed** 2020-05-06 14:24 UTC
