### ISSUE TITLE
Unresponsive Kernels during CNMF - dev version

### ISSUE THREAD

**Issue by chrisda13** [DeniseCaiLab/minian#49] opened 2020-03-10 21:56 UTC
I am having issues when I get to the CNMF step of the pipeline both with the demo and with my own data. When I am running the kernels under "test parameters for spatial update" or "test parameters for temporal update" the kernel gets stuck and never finishes. It will stop at some percentage and the timer will continue to count, but no progress will be made.

It does not occur at the same kernel every time, and when it is able to complete the kernel, it finishes relatively quickly. I have tried letting it run for 48 hours after getting stuck and it never finishes. This has occurred on multiple powerful machines (both windows and mac). I also tried running it on linux through a virtual box within a windows machine, and the same thing happened, although it got further (got stuck on the 2nd temporal update).

I never get an error message, the kernel just becomes unresponsive. Any idea what might be causing this?

I am running on the dev branch as recommended.

Thanks!!

**Comment by phildong** [comment] 2020-03-25 14:44
Hey, sorry for the belated reply.
Any chance this is a duplicate of #45 ?
If so I just posted another potential fix there. If you don't mind could you give that a try and let me know?

**Comment by cineguerrilha** [comment] 2020-04-25 17:57
same thing in here

**Comment by wmau** [comment] 2020-05-06 14:29
See #45 for a temporary fix. We are working with a team of software engineers to come up with a more permanent solution.

**Closed by wmau** 2020-05-06 14:29 UTC
